var lis  = [
    {
        "Departamento": "Acreditaciones y Certificacion",
        "ID": 1,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Administracion General Campus",
        "ID": 2,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Administracion y Finanzas",
        "ID": 3,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Administracion y Mercadotecnia",
        "ID": 4,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 1,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Admon de Instituciones (ESDAI)",
        "ID": 5,
        "Fumas": 2,
        "Alcohol": 4,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 2,
        "Faringitis o amigdalitis": 1,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 1,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": 1,
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Admon y Recursos Humanos",
        "ID": 6,
        "Fumas": 0,
        "Alcohol": 2,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Alumni",
        "ID": 7,
        "Fumas": 1,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 2,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Arte y Cultura",
        "ID": 8,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Asesoria Univ. y Convivencias",
        "ID": 9,
        "Fumas": 1,
        "Alcohol": 2,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Becas y Creditos",
        "ID": 10,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Biblioteca",
        "ID": 11,
        "Fumas": 1,
        "Alcohol": 4,
        "Asma": 0,
        "Sinusitis": 4,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 1,
        "Faringitis o amigdalitis": 1,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Biblioteca y Tec Educativa",
        "ID": 12,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Capellania",
        "ID": 13,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Centro de Lenguas",
        "ID": 14,
        "Fumas": 0,
        "Alcohol": 2,
        "Asma": 0,
        "Sinusitis": 3,
        "Gastritis": 0,
        "Epilepsia": 1,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 3,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 1,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Compras",
        "ID": 15,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Compromiso Social",
        "ID": 16,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 1,
        "Sinusitis": 0,
        "Gastritis": 1,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Comunicacion Institucional",
        "ID": 17,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Comunicacion, Publicidad y RP",
        "ID": 18,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 2,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 2,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 1,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Contabilidad",
        "ID": 19,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 1,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Contaduria",
        "ID": 20,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 1,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Corp. Promocion Internacional",
        "ID": 21,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Departamento de Humanidades",
        "ID": 22,
        "Fumas": 1,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 1,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 1,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Deportes",
        "ID": 23,
        "Fumas": 0,
        "Alcohol": 3,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 2,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 2,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 1,
        "Ginecologicas": 0,
        "Rinitis alergica": 1,
        "Tos cronica": 0,
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Derecho",
        "ID": 24,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Dir. Inst. de Investigacion",
        "ID": 25,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 1,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 1,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 1,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Dir.Institucional de Proyectos",
        "ID": 26,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 1,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Direccion Admtva. de Campus",
        "ID": 27,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 1,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Direccion de Area ECEE",
        "ID": 28,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 1,
        "Epilepsia": 0,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 1,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": 0,
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Direccion de Vinculacion",
        "ID": 29,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 1,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Direccion Empresas Familiares",
        "ID": 30,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Direccion Juridica",
        "ID": 31,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 1,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Direccion Posgrados ECEE",
        "ID": 32,
        "Fumas": 0,
        "Alcohol": 2,
        "Asma": 1,
        "Sinusitis": 1,
        "Gastritis": 4,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Fortalecimiento Academico",
        "ID": 33,
        "Fumas": 0,
        "Alcohol": 2,
        "Asma": 1,
        "Sinusitis": 0,
        "Gastritis": 1,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 1,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Grupos Estudiantiles",
        "ID": 34,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Ing Sistemas Computacionales",
        "ID": 35,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Ing. en Innovacion y Diseno",
        "ID": 36,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Ing.en Animacion Digital",
        "ID": 37,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 1,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Ingenieria Civil y Administrat",
        "ID": 38,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Ingenieria Mecatronica",
        "ID": 39,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "International Affairs",
        "ID": 40,
        "Fumas": 0,
        "Alcohol": 2,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Maestria en Capital Humano",
        "ID": 41,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 1,
        "Calculos vias urinarias": 0,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Maestria en Comercializacion",
        "ID": 42,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Maestria en Contraloria",
        "ID": 43,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 1,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Mantenimiento",
        "ID": 44,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Nominas",
        "ID": 45,
        "Fumas": 0,
        "Alcohol": 2,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 2,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Obras de Infraestructura",
        "ID": 46,
        "Fumas": 0,
        "Alcohol": 3,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 1,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Operaciones",
        "ID": 47,
        "Fumas": 1,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Planeacion Financiera",
        "ID": 48,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 1,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Poliforum Panamericano",
        "ID": 49,
        "Fumas": 1,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Posgrado en Comunicacion Est",
        "ID": 50,
        "Fumas": 1,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Posgrados en Derecho",
        "ID": 51,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Posgrados en Ingenieria",
        "ID": 52,
        "Fumas": 1,
        "Alcohol": 4,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 1,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 1,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Promocion y Admisiones",
        "ID": 53,
        "Fumas": 0,
        "Alcohol": 2,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 1,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Psicopedagogia",
        "ID": 54,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 1,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 1,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Rectoria de Campus",
        "ID": 55,
        "Fumas": 0,
        "Alcohol": 2,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 2,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Recursos Humanos",
        "ID": 56,
        "Fumas": 1,
        "Alcohol": 4,
        "Asma": 0,
        "Sinusitis": 2,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 1,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 1,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Salud y Bienestar Universitari",
        "ID": 57,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 1,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Secretaria Academica DER",
        "ID": 58,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Secretaria Academica ECEE",
        "ID": 59,
        "Fumas": 0,
        "Alcohol": 7,
        "Asma": 1,
        "Sinusitis": 0,
        "Gastritis": 3,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 2,
        "Faringitis o amigdalitis": 0,
        "Colitis": 1,
        "Convulsiones": 0,
        "Dermatologicos": 1,
        "Alteraciones en oidos": 2,
        "Trigliceridos altos": 2,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": 0,
        "Tos cronica": 2,
        "Ulcera gastrica": 0,
        "Desmayos (Sincope)": 1,
        "Conjuntivitis": 1,
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Secretaria Academica PED",
        "ID": 60,
        "Fumas": 1,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 1,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 2,
        "Problemas renales": 0,
        "Bronquitis": 1,
        "Faringitis o amigdalitis": 0,
        "Colitis": 1,
        "Convulsiones": 0,
        "Dermatologicos": 1,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Secretaria Administrativa Der",
        "ID": 61,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Secretaria Administrativa PED",
        "ID": 62,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 1,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Seguridad",
        "ID": 63,
        "Fumas": 4,
        "Alcohol": 5,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 2,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 3,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 2,
        "Ginecologicas": 2,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Servicios escolares",
        "ID": 64,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 1,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 2,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 1,
        "Colitis": 1,
        "Convulsiones": 1,
        "Dermatologicos": 2,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": 1,
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Spark UP",
        "ID": 65,
        "Fumas": 0,
        "Alcohol": 2,
        "Asma": 0,
        "Sinusitis": 2,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 2,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Sria Academica COM",
        "ID": 66,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 1,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Sria Academica Facd Ingenieria",
        "ID": 67,
        "Fumas": 1,
        "Alcohol": 7,
        "Asma": 1,
        "Sinusitis": 1,
        "Gastritis": 1,
        "Epilepsia": 0,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 1,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 2,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": 1,
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Sria Adtva. Facd. Ingenieria",
        "ID": 68,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Sria Asuntos Estudiantile ECEE",
        "ID": 69,
        "Fumas": 2,
        "Alcohol": 6,
        "Asma": 0,
        "Sinusitis": 2,
        "Gastritis": 4,
        "Epilepsia": 0,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 5,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 2,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Sria Asuntos Estudiantiles ESI",
        "ID": 70,
        "Fumas": 0,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Tecnologia Educativa",
        "ID": 71,
        "Fumas": 1,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 1,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Tecnologias de Informacion",
        "ID": 72,
        "Fumas": 2,
        "Alcohol": 2,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 1,
        "Faringitis o amigdalitis": 0,
        "Colitis": 1,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 1,
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Tesoreria",
        "ID": 73,
        "Fumas": 0,
        "Alcohol": 5,
        "Asma": 1,
        "Sinusitis": 1,
        "Gastritis": 4,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 1,
        "Problemas renales": 4,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 1,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": 0,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 0,
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Vicerrectoria Academica A",
        "ID": 74,
        "Fumas": 0,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 1,
        "Gastritis": 1,
        "Epilepsia": 0,
        "Hemorragias": 1,
        "Alteraciones en presion arterial": 1,
        "Colesterol alto": 0,
        "Problemas renales": 1,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 1,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 1,
        "Trigliceridos altos": 1,
        "Calculos vias urinarias": 0,
        "Ginecologicas": 1,
        "Rinitis alergica": 0,
        "Tos cronica": 0,
        "Ulcera gastrica": 1,
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Vicerrectoria de Investigacion",
        "ID": 75,
        "Fumas": 1,
        "Alcohol": 1,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 1,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": 0,
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    },
    {
        "Departamento": "Vida Universitaria",
        "ID": 76,
        "Fumas": 1,
        "Alcohol": 0,
        "Asma": 0,
        "Sinusitis": 0,
        "Gastritis": 0,
        "Epilepsia": 0,
        "Hemorragias": 0,
        "Alteraciones en presion arterial": 0,
        "Colesterol alto": 0,
        "Problemas renales": 0,
        "Bronquitis": 0,
        "Faringitis o amigdalitis": 0,
        "Colitis": 0,
        "Convulsiones": 0,
        "Dermatologicos": 0,
        "Alteraciones en oidos": "0",
        "Trigliceridos altos": "0",
        "Calculos vias urinarias": "0",
        "Ginecologicas": "0",
        "Rinitis alergica": "0",
        "Tos cronica": "0",
        "Ulcera gastrica": "0",
        "Desmayos (Sincope)": "0",
        "Conjuntivitis": "0",
        "Diabetes": "0",
        "Cardiovasculares": "0",
        "Calculos vesicula": "0",
        "Problemas oseos, musculares o articulares": "0",
        "Alteraciones psicologicas (depresion, ansiedad u otras)": "0"
    }
];


