//X<script src="lista.js"></script>
/*
<html>
<script src="lista.js"></script>>
</html>

$( document ).ready(function() {
    console.log( "ready!" );
});

*/


function next() {

  var elemen = document.getElementById("display");
  if (elemen.style.visibility === "hidden") {
    elemen.style.visibility = "visible";

  }else{
    elemen.style.visibility = "visible";
  }

}

function info(event){

  //v=false;

  var caja= document.getElementById("display");

  var listado, i, j, x = "";
  var src = event.target;
  var numero = src.innerText;


  console.log('funcion info');
  console.log(numero);

  var lis  = [
      {
          "Departamento": "Acreditaciones y Certificacion",
          "ID": 1,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Administracion General Campus",
          "ID": 2,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 1,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Administracion y Finanzas",
          "ID": 3,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Administracion y Mercadotecnia",
          "ID": 4,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 1,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Admon de Instituciones (ESDAI)",
          "ID": 5,
          "Fumas": 2,
          "Alcohol": 4,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 2,
          "Faringitis": 1,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 1,
          "oidos": 1,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": 1,
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Admon y Recursos Humanos",
          "ID": 6,
          "Fumas": 0,
          "Alcohol": 2,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Alumni",
          "ID": 7,
          "Fumas": 1,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 2,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Arte y Cultura",
          "ID": 8,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 1,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Asesoria Univ. y Convivencias",
          "ID": 9,
          "Fumas": 1,
          "Alcohol": 2,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Becas y Creditos",
          "ID": 10,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Biblioteca",
          "ID": 11,
          "Fumas": 1,
          "Alcohol": 4,
          "Asma": 0,
          "Sinusitis": 4,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 1,
          "Faringitis": 1,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Biblioteca y Tec Educativa",
          "ID": 12,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Capellania",
          "ID": 13,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Centro de Lenguas",
          "ID": 14,
          "Fumas": 0,
          "Alcohol": 2,
          "Asma": 0,
          "Sinusitis": 3,
          "Gastritis": 0,
          "Epilepsia": 1,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 3,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 1,
          "Trigliceridos": 0,
          "Calculos": 1,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Compras",
          "ID": 15,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Compromiso Social",
          "ID": 16,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 1,
          "Sinusitis": 0,
          "Gastritis": 1,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Comunicacion Institucional",
          "ID": 17,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Comunicacion, Publicidad y RP",
          "ID": 18,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 2,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 2,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 1,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Contabilidad",
          "ID": 19,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 1,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Contaduria",
          "ID": 20,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 1,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Corp. Promocion Internacional",
          "ID": 21,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Departamento de Humanidades",
          "ID": 22,
          "Fumas": 1,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 1,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 1,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Deportes",
          "ID": 23,
          "Fumas": 0,
          "Alcohol": 3,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 1,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 2,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 2,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 1,
          "Trigliceridos": 0,
          "Calculos": 1,
          "Ginecologicas": 0,
          "Rinitis": 1,
          "Tos": 0,
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Derecho",
          "ID": 24,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Dir. Inst. de Investigacion",
          "ID": 25,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 1,
          "Hemorragias": 1,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 1,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 1,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Dir.Institucional de Proyectos",
          "ID": 26,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 1,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Direccion Admtva. de Campus",
          "ID": 27,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 1,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Direccion de Area ECEE",
          "ID": 28,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 1,
          "Epilepsia": 0,
          "Hemorragias": 1,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 1,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 1,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": 0,
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Direccion de Vinculacion",
          "ID": 29,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 1,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Direccion Empresas Familiares",
          "ID": 30,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Direccion Juridica",
          "ID": 31,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 1,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Direccion Posgrados ECEE",
          "ID": 32,
          "Fumas": 0,
          "Alcohol": 2,
          "Asma": 1,
          "Sinusitis": 1,
          "Gastritis": 4,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 1,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Fortalecimiento Academico",
          "ID": 33,
          "Fumas": 0,
          "Alcohol": 2,
          "Asma": 1,
          "Sinusitis": 0,
          "Gastritis": 1,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 1,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Grupos Estudiantiles",
          "ID": 34,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Ing Sistemas Computacionales",
          "ID": 35,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Ing. en Innovacion y Diseno",
          "ID": 36,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Ing.en Animacion Digital",
          "ID": 37,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 1,
          "Hemorragias": 1,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Ingenieria Civil y Administrat",
          "ID": 38,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Ingenieria Mecatronica",
          "ID": 39,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "International Affairs",
          "ID": 40,
          "Fumas": 0,
          "Alcohol": 2,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Maestria en Capital Humano",
          "ID": 41,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 1,
          "Calculos": 0,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Maestria en Comercializacion",
          "ID": 42,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Maestria en Contraloria",
          "ID": 43,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 1,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Mantenimiento",
          "ID": 44,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Nominas",
          "ID": 45,
          "Fumas": 0,
          "Alcohol": 2,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 2,
          "Hemorragias": 1,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Obras de Infraestructura",
          "ID": 46,
          "Fumas": 0,
          "Alcohol": 3,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 1,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Operaciones",
          "ID": 47,
          "Fumas": 1,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Planeacion Financiera",
          "ID": 48,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 1,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Poliforum Panamericano",
          "ID": 49,
          "Fumas": 1,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Posgrado en Comunicacion Est",
          "ID": 50,
          "Fumas": 1,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Posgrados en Derecho",
          "ID": 51,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 1,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 1,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Posgrados en Ingenieria",
          "ID": 52,
          "Fumas": 1,
          "Alcohol": 4,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 1,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 1,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Promocion y Admisiones",
          "ID": 53,
          "Fumas": 0,
          "Alcohol": 2,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 1,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Psicopedagogia",
          "ID": 54,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 1,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 1,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Rectoria de Campus",
          "ID": 55,
          "Fumas": 0,
          "Alcohol": 2,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 2,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Recursos Humanos",
          "ID": 56,
          "Fumas": 1,
          "Alcohol": 4,
          "Asma": 0,
          "Sinusitis": 2,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 1,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 1,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 1,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Salud y Bienestar Universitari",
          "ID": 57,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 1,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Secretaria Academica DER",
          "ID": 58,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Secretaria Academica ECEE",
          "ID": 59,
          "Fumas": 0,
          "Alcohol": 7,
          "Asma": 1,
          "Sinusitis": 0,
          "Gastritis": 3,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 2,
          "Faringitis": 0,
          "Colitis": 1,
          "Convulsiones": 0,
          "Dermatologicos": 1,
          "oidos": 2,
          "Trigliceridos": 2,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": 0,
          "Tos": 2,
          "Ulcera": 0,
          "Desmayos": 1,
          "Conjuntivitis": 1,
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Secretaria Academica PED",
          "ID": 60,
          "Fumas": 1,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 1,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 2,
          "renales": 0,
          "Bronquitis": 1,
          "Faringitis": 0,
          "Colitis": 1,
          "Convulsiones": 0,
          "Dermatologicos": 1,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Secretaria Administrativa Der",
          "ID": 61,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Secretaria Administrativa PED",
          "ID": 62,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 1,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 1,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Seguridad",
          "ID": 63,
          "Fumas": 4,
          "Alcohol": 5,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 2,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 3,
          "oidos": 1,
          "Trigliceridos": 0,
          "Calculos": 2,
          "Ginecologicas": 2,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Servicios escolares",
          "ID": 64,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 1,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 2,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 1,
          "Colitis": 1,
          "Convulsiones": 1,
          "Dermatologicos": 2,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": 1,
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Spark UP",
          "ID": 65,
          "Fumas": 0,
          "Alcohol": 2,
          "Asma": 0,
          "Sinusitis": 2,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 2,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Sria Academica COM",
          "ID": 66,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 1,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 1,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Sria Academica Facd Ingenieria",
          "ID": 67,
          "Fumas": 1,
          "Alcohol": 7,
          "Asma": 1,
          "Sinusitis": 1,
          "Gastritis": 1,
          "Epilepsia": 0,
          "Hemorragias": 1,
          "Alteraciones": 1,
          "Colesterol": 1,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 2,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": 1,
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Sria Adtva. Facd. Ingenieria",
          "ID": 68,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Sria Asuntos Estudiantile ECEE",
          "ID": 69,
          "Fumas": 2,
          "Alcohol": 6,
          "Asma": 0,
          "Sinusitis": 2,
          "Gastritis": 4,
          "Epilepsia": 0,
          "Hemorragias": 1,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 5,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 2,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Sria Asuntos Estudiantiles ESI",
          "ID": 70,
          "Fumas": 0,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Tecnologia Educativa",
          "ID": 71,
          "Fumas": 1,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 1,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Tecnologias de Informacion",
          "ID": 72,
          "Fumas": 2,
          "Alcohol": 2,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 1,
          "Faringitis": 0,
          "Colitis": 1,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 1,
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Tesoreria",
          "ID": 73,
          "Fumas": 0,
          "Alcohol": 5,
          "Asma": 1,
          "Sinusitis": 1,
          "Gastritis": 4,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 1,
          "renales": 4,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 1,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": 0,
          "Calculos": 0,
          "Ginecologicas": 0,
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Vicerrectoria Academica A",
          "ID": 74,
          "Fumas": 0,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 1,
          "Gastritis": 1,
          "Epilepsia": 0,
          "Hemorragias": 1,
          "Alteraciones": 1,
          "Colesterol": 0,
          "renales": 1,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 1,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 1,
          "Trigliceridos": 1,
          "Calculos": 0,
          "Ginecologicas": 1,
          "Rinitis": 0,
          "Tos": 0,
          "Ulcera": 1,
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Vicerrectoria de Investigacion",
          "ID": 75,
          "Fumas": 1,
          "Alcohol": 1,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 1,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": 0,
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      },
      {
          "Departamento": "Vida Universitaria",
          "ID": 76,
          "Fumas": 1,
          "Alcohol": 0,
          "Asma": 0,
          "Sinusitis": 0,
          "Gastritis": 0,
          "Epilepsia": 0,
          "Hemorragias": 0,
          "Alteraciones": 0,
          "Colesterol": 0,
          "renales": 0,
          "Bronquitis": 0,
          "Faringitis": 0,
          "Colitis": 0,
          "Convulsiones": 0,
          "Dermatologicos": 0,
          "oidos": "0",
          "Trigliceridos": "0",
          "Calculos": "0",
          "Ginecologicas": "0",
          "Rinitis": "0",
          "Tos": "0",
          "Ulcera": "0",
          "Desmayos": "0",
          "Conjuntivitis": "0",
          "Diabetes": "0",
          "Cardiovasculares": "0",
          "vesicula": "0",
          "Problemas": "0",
          "psicologicas": "0"
      }
  ];


  for (i in lis) {
    if(numero==lis[i].Departamento){
      v=true;
/*
      if (v==true) {
        $("BUTTON").click(function(){

          $("#btn1").toggleClass("btn-danger btn-success");
      });
*/
      


      console.log('entro');
      x += "<h2>" + lis[i].Departamento + "</h2>"+ "<br>";

      if(lis[i].Fumas==0){ }else{x +=  "Fuman:" + lis[i].Fumas + "<br>";}
      if(lis[i].Alcohol==0){ }else{x +=  "Toman:" + lis[i].Alcohol + "<br>";}
      if(lis[i].Asma==0){ }else{x +=  "Asma:" + lis[i].Asma + "<br>";}
      if(lis[i].Sinusitis==0){ }else{x +=  "Sinusitis:" + lis[i].Sinusitis + "<br>";}
      if(lis[i].Gastritis==0){ }else{x +=  "Gastritis:" + lis[i].Gastritis + "<br>";}
      if(lis[i].Epilepsia==0){ }else{x +=  "Epilepsia:" + lis[i].Epilepsia + "<br>";}
      if(lis[i].Hemorragias==0){ }else{x +=  "Hemorragias:" + lis[i].Hemorragias + "<br>";}
      if(lis[i].Alteraciones==0){ }else{x +=  "Alteraciones en presion arterial:" + lis[i].Alteraciones + "<br>";}
      if(lis[i].Colesterol==0){ }else{x +=  "Colesterol alto:" + lis[i].Colesterol + "<br>";}
      if(lis[i].renales==0){ }else{x +=  "Problemas renales:" + lis[i].renales + "<br>";}
      if(lis[i].Bronquitis==0){ }else{x +=  "Bronquitis:" + lis[i].Bronquitis + "<br>";}
      if(lis[i].Faringitis==0){ }else{x +=  "Faringitis o amigdalitis:" + lis[i].Faringitis + "<br>";}
      if(lis[i].Colitis==0){ }else{x +=  "Colitis:" + lis[i].Colitis + "<br>";}
      if(lis[i].Colitis==0){ }else{x +=  "Colitis:" + lis[i].Colitis + "<br>";}
      if(lis[i].Dermatologicos==0){ }else{x +=  "Dermatologicos:" + lis[i].Dermatologicos + "<br>";}
      if(lis[i].oidos==0){ }else{x +=  "Alteraciones en oidos:" + lis[i].oidos + "<br>";}
      if(lis[i].Trigliceridos==0){ }else{x +=  "Trigliceridos altos:" + lis[i].Trigliceridos + "<br>";}
      if(lis[i].Calculos==0){ }else{x +=  "Calculos vias urinarias:" + lis[i].Calculos + "<br>";}
      if(lis[i].Ginecologicas==0){ }else{x +=  "Ginecologicas:" + lis[i].Ginecologicas + "<br>";}
      if(lis[i].Rinitis==0){ }else{x +=  "Rinitis alergica:" + lis[i].Rinitis + "<br>";}
      if(lis[i].Tos==0){ }else{x +=  "Tos cronica:" + lis[i].Tos + "<br>";}
      if(lis[i].Ulcera==0){ }else{x +=  "Ulcera gastrica:" + lis[i].Ulcera + "<br>";}
      if(lis[i].Desmayos==0){ }else{x +=  "Desmayos (Sincope):" + lis[i].Desmayos + "<br>";}
      if(lis[i].Conjuntivitis==0){ }else{x +=  "Conjuntivitis:" + lis[i].Conjuntivitis + "<br>";}
      if(lis[i].Diabetes==0){ }else{x +=  "Diabetes:" + lis[i].Diabetes + "<br>";}
      if(lis[i].Cardiovasculares==0){ }else{x +=  "Cardiovasculares:" + lis[i].Cardiovasculares + "<br>";}
      if(lis[i].vesicula==0){ }else{x +=  "Calculos vesicula:" + lis[i].vesicula + "<br>";}
      if(lis[i].Problemas==0){ }else{x +=  "Problemas:" + lis[i].Problemas + "<br>";}
      if(lis[i].psicologicas==0){ }else{x +=  "Alteraciones psicologicas (depresion, ansiedad u otras):" + lis[i].psicologicas + "<br>";}

    }
  }

  for (i in lis) {
    if(numero==lis[i].ID){
      console.log('entro');
      x += "<h2>" + lis[i].Departamento + "</h2>"+ "<br>";

      if(lis[i].Fumas==0){ }else{x +=  "Fuman:" + lis[i].Fumas + "<br>";}
      if(lis[i].Alcohol==0){ }else{x +=  "Toman:" + lis[i].Alcohol + "<br>";}
      if(lis[i].Asma==0){ }else{x +=  "Asma:" + lis[i].Asma + "<br>";}
      if(lis[i].Sinusitis==0){ }else{x +=  "Sinusitis:" + lis[i].Sinusitis + "<br>";}
      if(lis[i].Gastritis==0){ }else{x +=  "Gastritis:" + lis[i].Gastritis + "<br>";}
      if(lis[i].Epilepsia==0){ }else{x +=  "Epilepsia:" + lis[i].Epilepsia + "<br>";}
      if(lis[i].Hemorragias==0){ }else{x +=  "Hemorragias:" + lis[i].Hemorragias + "<br>";}
      if(lis[i].Alteraciones==0){ }else{x +=  "Alteraciones en presion arterial:" + lis[i].Alteraciones + "<br>";}
      if(lis[i].Colesterol==0){ }else{x +=  "Colesterol alto:" + lis[i].Colesterol + "<br>";}
      if(lis[i].renales==0){ }else{x +=  "Problemas renales:" + lis[i].renales + "<br>";}
      if(lis[i].Bronquitis==0){ }else{x +=  "Bronquitis:" + lis[i].Bronquitis + "<br>";}
      if(lis[i].Faringitis==0){ }else{x +=  "Faringitis o amigdalitis:" + lis[i].Faringitis + "<br>";}
      if(lis[i].Colitis==0){ }else{x +=  "Colitis:" + lis[i].Colitis + "<br>";}
      if(lis[i].Colitis==0){ }else{x +=  "Colitis:" + lis[i].Colitis + "<br>";}
      if(lis[i].Dermatologicos==0){ }else{x +=  "Dermatologicos:" + lis[i].Dermatologicos + "<br>";}
      if(lis[i].oidos==0){ }else{x +=  "Alteraciones en oidos:" + lis[i].oidos + "<br>";}
      if(lis[i].Trigliceridos==0){ }else{x +=  "Trigliceridos altos:" + lis[i].Trigliceridos + "<br>";}
      if(lis[i].Calculos==0){ }else{x +=  "Calculos vias urinarias:" + lis[i].Calculos + "<br>";}
      if(lis[i].Ginecologicas==0){ }else{x +=  "Ginecologicas:" + lis[i].Ginecologicas + "<br>";}
      if(lis[i].Rinitis==0){ }else{x +=  "Rinitis alergica:" + lis[i].Rinitis + "<br>";}
      if(lis[i].Tos==0){ }else{x +=  "Tos cronica:" + lis[i].Tos + "<br>";}
      if(lis[i].Ulcera==0){ }else{x +=  "Ulcera gastrica:" + lis[i].Ulcera + "<br>";}
      if(lis[i].Desmayos==0){ }else{x +=  "Desmayos (Sincope):" + lis[i].Desmayos + "<br>";}
      if(lis[i].Conjuntivitis==0){ }else{x +=  "Conjuntivitis:" + lis[i].Conjuntivitis + "<br>";}
      if(lis[i].Diabetes==0){ }else{x +=  "Diabetes:" + lis[i].Diabetes + "<br>";}
      if(lis[i].Cardiovasculares==0){ }else{x +=  "Cardiovasculares:" + lis[i].Cardiovasculares + "<br>";}
      if(lis[i].vesicula==0){ }else{x +=  "Calculos vesicula:" + lis[i].vesicula + "<br>";}
      if(lis[i].Problemas==0){ }else{x +=  "Problemas:" + lis[i].Problemas + "<br>";}
      if(lis[i].psicologicas==0){ }else{x +=  "Alteraciones psicologicas (depresion, ansiedad u otras):" + lis[i].psicologicas + "<br>";}

    }
  }
			/*document.getElementById("demo").innerHTML = x;*/
			caja.innerHTML=x;

      console.log('eureka');
}

  /*
document.getElementById("demo").innerHTML = "You selected: " + x;


  function prueba1(){var cosa= document.getElementById("BtnIni_1").innerText; document.getElementById("demo").innerHTML = "You selected: " + cosa;}












  //--------------------------------------

              x +="inetnt"+ lis[i] + "<br>";
              document.getElementById("demo").innerHTML = lis["Departamento"];
              x +="inetnt"+ lis[i] + "<br>";




  						x += lis[i].Departamento+ "<br>";
  		        x += lis[i].fum+ "<br>";

  		    		for (j in lis) {
  		        		x += lis[i].Departamento + "<br>";
  		    				}
  		enfer= [
  	    	    {"id":"1", "nombre":"departamento 1", "alc":"3 toman", "fum":"31 fuman", "enf":[" 3 personas con diarrea", "2 perdonas con sueño"]},
  	    	    {"id":"2", "nombre":"departamento 2", "alc":"1 toman", "fum":"24 fuman", "enf":[" 5 personas con droga", "5 perdonas con insomnio"]},
  	            {"id":"3", "nombre":"departamento 3", "alc":"2 toman", "fum":"12 fuman", "enf":[" 3 personas con gastritis", "22 perdonas con garfantitis"]},
  				{"id":"4", "nombre":"departamento 4", "alc":"9 toman", "fum":"11 fuman", "enf":[" 4 personas con diarrea", "4 perdonas con ojos latos"]},
  				{"id":"5", "nombre":"departamento 5", "alc":"3 toman", "fum":"1 fuman", "enf":[" 3 personas con diarrea", "2 perdonas con sueño"]},
  				{"id":"6", "nombre":"departamento 6", "alc":"1 toman", "fum":"24 fuman", "enf":[" 1 personas con droga", "50 perdonas con insomnio"]},
  				{"id":"7", "nombre":"departamento 7", "alc":"2 toman", "fum":"12 fuman", "enf":[" 3 personas con gastritis", "2 perdonas con garfantitis"]},
  				{"id":"8", "nombre":"departamento 8", "alc":"9 toman", "fum":"11 fuman", "enf":[" 0 personas con diarrea", "4 perdonas con ojos latos"]},
  				{"id":"9", "nombre":"departamento 9", "alc":"3 toman", "fum":"31 fuman", "enf":[" 3 personas con diarrea", "2 perdonas con sueño"]},
  				{"id":"10", "nombre":"departamento 10", "alc":"1 toman", "fum":"24 fuman", "enf":[" 11 personas con droga", "7 perdonas con insomnio"]}


  	    ]


  for (i in enfer) {
        if(numero==enfer[i].id){
          console.log('entro');
          x += "<h2>" + enfer[i].nombre + "</h2>"+ "<br>";
          x += enfer[i].alc+ "<br>";
          x += enfer[i].fum+ "<br>";

          for (j in enfer[i].enf) {
              x += enfer[i].enf[j] + "<br>";
              }
        }
  }
  */
